Handle unmapped routes
clayallsopp/Routable pull request #10
Opened 2017-02-06 05:32 UTC by afestein

At the moment, every supported URL has to be explicitly mapped, otherwise the
app crashes and raises an exception. The more user-friendly option would be to
fail to open the URL without crashing the app.

2017-02-07 01:54 UTC, felixclack approved these changes

2017-02-14 03:05 UTC, felixclack requested changes

2017-02-14 03:05 UTC, felixclack commented on lib/routable/router.rb
> +      if self.routes.exclude? url
Looks like this stops the matching of named parameters.

2017-03-05 23:21 UTC, afestein commented
It doesn't look like this gem is maintained so we might need to run with our own fork for now.

2017-03-05 23:21 UTC, closed without merging